package utils

const (
	USER_NOT_FOUND           = "USER_NOT_FOUND"
	USER_ALREADY_EXISTS      = "USER_ALREADY_EXISTS"
	USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS"
	EVENT_NOT_FOUND       = "EVENT_NOT_FOUND"
	EVENT_INVALID_ID      = "EVENT_INVALID_ID"
	EVENT_CREATE_FAILED   = "EVENT_CREATE_FAILED"
	EVENT_UPDATE_FAILED   = "EVENT_UPDATE_FAILED"
	EVENT_DELETE_FAILED   = "EVENT_DELETE_FAILED"
	BOOKING_NOT_FOUND        = "BOOKING_NOT_FOUND"
	BOOKING_INVALID_ID       = "BOOKING_INVALID_ID"
	BOOKING_CREATE_FAILED    = "BOOKING_CREATE_FAILED"
	BOOKING_NOT_ENOUGH_TICKETS = "NOT_ENOUGH_TICKETS"
	BOOKING_ALREADY_CANCELLED = "BOOKING_ALREADY_CANCELLED"
	BOOKING_ALREADY_CONFIRMED = "BOOKING_ALREADY_CONFIRMED"
	BOOKING_EXPIRED          = "BOOKING_EXPIRED"
	BOOKING_CANCEL_FAILED    = "BOOKING_CANCEL_FAILED"
	INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
)
